# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-csslint
  sha: v1.0.5
  hooks:
    - id: csslint
- repo: https://github.com/dnephin/pre-commit-golang
  sha: HEAD
  hooks:
    - id: validate-toml
