# .travis.yml
dist: trusty
sudo: required

git:
  depth: 10

branches:
  only:
    - master

install:
 - wget -O /tmp/hugo.deb https://github.com/spf13/hugo/releases/download/v0.21/hugo_0.21_Linux-64bit.deb
 - sudo dpkg -i /tmp/hugo.deb

script:
 - hugo
