baseURL = "http://www.dreisbach.us/"
languageCode = "en-us"
title = "Clinton Dreisbach"
theme = "blank"
paginate = 7
sectionPagesMenu = "main"

[params]
author = "Clinton Dreisbach"
copyright = "&copy; Clinton Dreisbach 2017"

[params.highlight]
style = "github"
languages = ["ruby", "python", "javascript", "bash"]

[[params.social]]
url = "https://github.com/cndreisbach"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/cndreisbach"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[[menu.main]]
name = "Articles"
weight = 10
identifier = "articles"
url = "/articles/"

[[menu.main]]
name = "Notes"
weight = 20
identifier = "notes"
url = "/notes/"

[[menu.main]]
name = "Games"
weight = 30
url = "/games/"

[[menu.main]]
name = "About"
weight = 100
url = "/about/"
