baseURL = "http://www.dreisbach.us/"
languageCode = "en-us"
title = "Clinton Dreisbach"
theme = "blank"
paginate = 7
sectionPagesMenu = "main"
metaDataFormat = "yaml"
pygmentsCodeFences = true
pygmentsStyle = "friendly"

[author]
name = "Clinton Dreisbach"
email = "clinton@dreisbach.us"

[params]
author = "Clinton Dreisbach"
copyright = "&copy; Clinton Dreisbach 2018"
mainSections = ["articles", "notes"]

[params.highlight]
style = "github"
languages = ["ruby", "python", "javascript", "bash"]

[[params.social]]
url = "https://github.com/cndreisbach"
fa_icon = "fa-github"

[[params.social]]
url = "https://soundcloud.com/mount-olive"
fa_icon = "fa-soundcloud"


[[menu.sidebar]]
name = "Articles"
weight = 10
identifier = "articles"
url = "/articles/"

[[menu.sidebar]]
name = "Notes"
weight = 20
identifier = "notes"
url = "/notes/"

[[menu.sidebar]]
name = "Games"
weight = 30
url = "/games/"

[[menu.sidebar]]
name = "Projects"
weight = 35
url = "/projects/"

[[menu.sidebar]]
name = "About"
weight = 40
url = "/about/"

# [[menu.sidebar]]
# name= "Now"
# weight = 50
# url = "/now/"
